config/routes.rb
KegeratorstatUs::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :kegerators do
    resources :kegs
  end
  resources :beer_requests, :only => [:new, :create]

  match 'status/:login' => 'status#for_user', :as => :status
  match 'content/:content' => "content#show", :as => :content

  root :to => 'status#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  has_many :kegs

  def to_s
    "#{brewery.name}: #{name}"
  end
end

app/models/beer_request.rb
class BeerRequest < ActiveRecord::Base
  belongs_to :user
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers
end

app/models/daily_stat.rb
class DailyStat < Struct.new(:date, :pints, :guesstimate)
end

app/models/keg.rb
class Keg < ActiveRecord::Base
  OUNCES_IN_A_GALLON = 128
  OUNCES_IN_A_PINT = 16
  OUNCES_IN_A_SIXPACK = ( 12 * 6 )

  belongs_to :keg_type
  belongs_to :kegerator
  belongs_to :beer

  has_one :user, :through => :kegerator

  before_save :set_added_at

  scope :finished, where("finished_at IS NOT NULL")
  scope :not_finished, where("finished_at IS NULL")
  scope :not_finished_on, lambda {|date| 
    where("(:date BETWEEN added_at AND finished_at AND finished_at IS NOT NULL) OR ( finished_at IS NULL AND added_at < :date)", :date => date)
  }

  def finished?
    finished_at.present?
  end

  def days_lasted
    finished_at - added_at
  end

  def consumed_per_day( uom = :pint )
    (((keg_type.capacity_in_gallons * OUNCES_IN_A_GALLON) / days_lasted ) / (uom == :pint ? OUNCES_IN_A_PINT : OUNCES_IN_A_SIXPACK)).round
  end

  def had_beer_on?( date )
    (added_at..finished_at).cover?(date)
  end

  def days_til_empty
    days = (estimated_lifetime - age)
    days < 0 ? 0 : days
  end

  def age
    (Date.today - added_at).to_i
  end

  def estimated_lifetime
    ((keg_type.capacity_in_gallons * OUNCES_IN_A_GALLON / OUNCES_IN_A_PINT) / user.average_daily_consumption).floor
  end

  protected
    def set_added_at
      self.added_at = Time.now unless added_at.present?
    end
end

app/models/keg_type.rb
class KegType < ActiveRecord::Base
  validates_uniqueness_of :name
  has_many :kegs
end

app/models/kegerator.rb
class Kegerator < ActiveRecord::Base
  belongs_to :user
  has_many :kegs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :login, :email
  validates_presence_of :login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login

  has_many :kegerators
  has_many :kegs, :through => :kegerators

  def drinking_stats( days_ago = 7 )
    start_date = days_ago.days.ago
    stop_date = Date.today

    kegs_full_in_range = kegs.where(:finished_at => (start_date..stop_date) )

    avg_consumption = average_daily_consumption

    days_ago.downto(0).inject([]) do |stats, days|
      date = days.days.ago.to_date
      
      stat = DailyStat.new(:date => date)

      stat.pints = kegs_full_in_range.select {|k| k.had_beer_on?(date) }.inject(0) {|pints, keg| pints + keg.consumed_per_day }
      if (tapped = tapped_kegs(date)).size > 0
        stat.pints += (tapped.size * avg_consumption)
        stat.guesstimate = true
      end


      stats << stat
    end
  end

  def average_daily_consumption( finished_kegs = kegs.finished.order(:finished_at).limit(10) )
    pints = finished_kegs.map(&:consumed_per_day)

    (pints.inject(0) {|sum, p| sum + p}.to_f / pints.size).ceil
  end
  # This needs to be a DB column, or memoized. This is probably a bitch of a data access call.

  def tapped_kegs_on?( date = Date.today )
    tapped_kegs(date).count > 0
  end

  def tapped_kegs( date = Date.today )
    kegs.not_finished_on(date)
  end

  
  def to_param
    login
  end

  def admin?
    email == 'jon@burningbush.us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
    def authenticate_admin!
      unless current_user.admin?
        redirect_to '/' and return false
      end
    end
end

app/controllers/beer_requests_controller.rb
class BeerRequestsController < ApplicationController
  inherit_resources

  before_filter :authenticate_user!

  actions :new, :create

  def create
    create! do |format|
      format.html do
        flash[:success] = "Request submitted!"
        Mailer.beer_request(@beer_request).deliver rescue nil
        redirect_to kegerators_path
      end
    end
  end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def show
    render params[:content]
  end
end

app/controllers/kegerators_controller.rb
class KegeratorsController < ApplicationController
  inherit_resources

  before_filter :authenticate_user!

  def create
    create! { kegerators_path }
  end

  def update 
    update! { kegerators_path }
  end

  protected
    def begin_of_association_chain
      current_user
    end
end

app/controllers/kegs_controller.rb
class KegsController < ApplicationController
  inherit_resources
  belongs_to :kegerator

  before_filter :authenticate_user!

  def create
    create! { kegerators_path }
  end

  def destroy
    destroy! { kegerators_path }
  end

  def update
    update! { kegerators_path }
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def index
    @kegs = Keg.order("updated_at desc").limit(15).includes(:user)
  end

  def for_user
    @user = User.where(:login => params[:login]).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_requests_helper.rb
module BeerRequestsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/kegerators_helper.rb
module KegeratorsHelper
end

app/helpers/kegs_helper.rb
module KegsHelper
  def fullness_class(keg)
    case keg.days_til_empty
    when 0
      'almost-empty'
    when 1..3
      'close-to-empty'
    end
  end
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/beer_requests/new.html.haml
%h2 Request a beer
%p Yeah, I'm lazy. I'll only go out and add the beers I drink. Make me add a new one.

= form_for @beer_request do |f|
  = hidden_field_tag "beer_request[user_id]", current_user.id
  = f.label :body, "About the beer. Brewery, name, URL, etc, etc"
  = f.text_area :body
  = f.submit "Request It!"

app/views/content/about.html.haml
%h2 About KegeratorStat.us

%h3 WTF is this bullshit?

%p
  Well. See. I have kegerator. A new one. It's awesome. You should buy one.

%p
  Specifically, you should buy one so that I can make a commision. Here's a coupon for $15 off if you spend
  three hundred bucks or more. Don't worry. You will.

  <a href="http://www.jdoqocy.com/click-5516923-10884176" target="_blank">Shop Kegerator.com for Additional $15 off orders $299+ with code K299NOV now thru 11/30</a><img src="http://www.ftjcfx.com/image-5516923-10884176" width="1" height="1" border="0"/>

%p 
  I'm also a giant geek, and I want to make pretty charts about how much I drink, and I want
  some sort of automated reminder that I should probably get beer soon.

%p
  Don't you?

%p
  So that's what this is. If you add your kegerator, and track when you fill it, and empty it, I promise to
  eventually have pretty statistics about just how much beer you drink, and do some sort of fancy remindering
  about buying beer.

%p
  I also promise to advertise the <b>shit</b> out of any beer or kegerator related affiliate programs I can find,
  but nothing that's going to drive you insane. Honest. I hate ads, but, well, I need beer money.

app/views/kegerators/_form.html.haml
= form_for @kegerator do |form|
  = form.label :name
  = form.text_field :name, :class => "input-text"
  = form.submit "Fill 'er up!"

app/views/kegerators/index.html.haml
%h2 
  Your Kegerators
  = link_to "add one", new_kegerator_path

%ul
  - @kegerators.each do |kegerator|
    %li
      = kegerator.name
      = link_to "Add a keg!", new_kegerator_keg_path(kegerator)

      %ul#kegs
        - if kegerator.kegs.not_finished.size.zero?
          %li
            %strong NO BEER? WHAT?!?
        - kegerator.kegs.not_finished.limit(10).each do |keg|
          %li.keg{:class => fullness_class(keg)}
            = "A #{keg.keg_type.name} of #{keg.beer} (#{keg.added_at})"
            = link_to_function "stuff", '$(this).next(".links").toggle()'
            .links{:style => "display: none;"}
              = link_to "destroy", kegerator_keg_path(kegerator, keg), :method => :delete, :confirm => "Are you sure you didn't just finish it?", :class => "nice small radius red button"
              = link_to "finished!", '#', :class => "nice small radius black button", :"data-reveal-id" => dom_id(keg, 'finished')
            .reveal-modal{:id => dom_id(keg, 'finished')}
              %a.close-reveal-modal &#215;

              = form_for [kegerator, keg] do |form|
                = form.label :finished_at
                = form.date_select :finished_at
                = form.submit "It's empty :("

        - kegerator.kegs.finished.each do |keg|
          %li.keg
            = "A #{keg.keg_type.name} of #{keg.beer} was finished on #{keg.finished_at}"
            %p{:style => "text-indent: 15px;"}
              It lasted #{((keg.finished_at - keg.added_at)).to_i} days, and you drank #{keg.consumed_per_day.round} pints a day.

#stats
  %p Here's how much you've been drinking lately.

  %table
    %thead
      %tr
        - 7.downto(0) do |days|
          %th= days.days.ago.to_date.strftime("%a, %d")
    %tbody
      %tr
        - current_user.drinking_stats.each do |stat|
          %td #{stat.pints} pints#{'*' if stat.guesstimate}
    %tfoot
      %tr
        %td{:colspan => 8} * means that we're just guess based on your drinking history and kegerator fullness.

app/views/kegerators/new.html.haml
%h2 Add a kegerator

= render "form"

app/views/kegs/_form.html.haml
= form_for [@kegerator, @keg] do |form|
  = form.label :keg_type_id
  = form.select :keg_type_id, options_from_collection_for_select(KegType.all, :id, :name), :include_blank => true
  = form.label :beer_id
  = form.select :beer_id, options_from_collection_for_select(Beer.all, :id, :to_s), :include_blank => true
  %p
    Can't find your beer? #{link_to "Make me add it!", new_beer_request_path}
  = link_to_function "Advanced options", "$('#advanced').toggle()"
  %br
  #advanced{:style => "display: none;"}
    = form.label "Added at:"
    = form.date_select :added_at
  = form.submit "Drink Up!"

app/views/kegs/new.html.haml
%h2 Add a keg to '#{@kegerator.name}'

= render "form"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title KegeratorstatUs
    
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
    - unless Rails.env.development?
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-122488-11']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

  %body
    .container
      .row
        .eight.columns
          #messages
            - %w( message success warning alert ).each do |key|
              - if flash[key.to_sym]
                .alert-box{:class => key}= flash[key.to_sym]

          = yield

        .four.columns
          %h3 Sidebar
          - if user_signed_in?
            %ul
              %li= link_to "Everybody's beer", root_path
              %li= link_to "Your Kegerators", kegerators_path
              %li= link_to "Account", edit_user_registration_path
              %li= link_to "Logout", destroy_user_session_path, :method => :delete
          - else
            = form_tag user_session_path do
              = label_tag "Email"
              = text_field_tag 'user[email]', '', :class => 'small input-text'
              = label_tag "Password"
              = password_field_tag 'user[password]', '', :class => "small input-text"
              %button Sign in
              %ul
                %li= link_to "Forgot your password?", new_password_path('user')
                %li= link_to "Signup!", new_user_registration_path
          = link_to "About", content_path(:about)
                        

          - unless Rails.env.development?
            :javascript
              google_ad_client = "ca-pub-4153439595195957";
              /* Kegerator Stat.us */
              google_ad_slot = "7720724225";
              google_ad_width = 300;
              google_ad_height = 250;
              //-->
    
            %h5{:style => "margin-top: 100px;"} Advertisments (beer money)
            <a href="http://www.anrdoezrs.net/click-5516923-10606124" target="_top"><img src="http://www.awltovhc.com/image-5516923-10606124" width="125" height="125" alt="" border="0"/></a>
            

            <script type="text/javascript"
            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
            </script>

app/views/status/for_user.html.haml
%h2 What's on tap at the house of #{@user.login}

- @user.kegerators.each do |kegerator|
  %h3= kegerator.name
  - if kegerator.kegs.not_finished.size.zero?
    %strong IT'S EMPTY!!!! *GASP*
  %ul
    - kegerator.kegs.not_finished.each do |keg|
      %li A delicious #{keg.keg_type.name} of #{keg.beer}
      

app/views/status/index.html.haml
%h2 Recent Activity

%ul
  - @kegs.each do |keg|
    %li #{link_to keg.user.login, status_path(keg.user)} #{keg.finished? ? 'finished' : 'added'} a #{keg.keg_type.name} of #{keg.beer}